name = "dokimos"
main = "worker/index.js"
compatibility_date = "2026-07-04"

[assets]
directory = "./"
binding = "ASSETS"
not_found_handling = "404-page"

[vars]
CONTACT_RECIPIENT = "info.charis.systems@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "dokimos-db"
database_id = "7700d105-2f39-4f06-83b4-cafb434e73b1"
migrations_dir = "migrations"
